name: Package Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev

jobs:
  test:
    name: Test package
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      ANSIBLE_LINT_VERSION: "6.16.0"
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run ansible-lint
        run: ansible-lint ansible