name: Upload to Galaxy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev

jobs:
  test:
    name: Upload
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Deploy Ansible Galaxy Collection
        uses: artis3n/ansible_galaxy_collection@v2.10.1